version: '3'
services:
  app:
    container_name: formatter
    build: .
    restart: on-failure
    environment:
      BLACK_PATH: black
      CLANG_FORMAT_PATH: clang-format
      DOTNET_PATH: dotnet
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: .
        target: /app
